version: "3.8"
services:
  localstack:
    image: localstack/localstack:2.0.2
    network_mode: bridge
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
    ports:
      - "4566:4566"
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
volumes:
  postgres:
    driver: local